export const paysList = [
    { nom: 'Niger', indicatif: '+227' },
    { nom: 'Sénégal', indicatif: '+221' },
    { nom: 'Côte d\'Ivoire', indicatif: '+225' },
    { nom: 'Mali', indicatif: '+223' },
    { nom: 'Burkina Faso', indicatif: '+226' },
    { nom: 'Ghana', indicatif: '+233' },
    { nom: 'Nigeria', indicatif: '+234' },
    { nom: 'Togo', indicatif: '+228' },
    { nom: 'Bénin', indicatif: '+229' },
    { nom: 'Cameroun', indicatif: '+237' },
    { nom: 'Afrique du Sud', indicatif: '+27' },
    { nom: 'Algérie', indicatif: '+213' },
    { nom: 'Angola', indicatif: '+244' },
    { nom: 'Botswana', indicatif: '+267' },
    { nom: 'Burundi', indicatif: '+257' },
    { nom: 'Cap-Vert', indicatif: '+238' },
    { nom: 'Comores', indicatif: '+269' },
    { nom: 'Djibouti', indicatif: '+253' },
    { nom: 'Égypte', indicatif: '+20' },
    { nom: 'Érythrée', indicatif: '+291' },
    { nom: 'Eswatini', indicatif: '+268' },
    { nom: 'Éthiopie', indicatif: '+251' },
    { nom: 'Gabon', indicatif: '+241' },
    { nom: 'Gambie', indicatif: '+220' },
    { nom: 'Guinée', indicatif: '+224' },
    { nom: 'Guinée-Bissau', indicatif: '+245' },
    { nom: 'Guinée équatoriale', indicatif: '+240' },
    { nom: 'Kenya', indicatif: '+254' },
    { nom: 'Lesotho', indicatif: '+266' },
    { nom: 'Liberia', indicatif: '+231' },
    { nom: 'Libye', indicatif: '+218' },
    { nom: 'Madagascar', indicatif: '+261' },
    { nom: 'Malawi', indicatif: '+265' },
    { nom: 'Maroc', indicatif: '+212' },
    { nom: 'Maurice', indicatif: '+230' },
    { nom: 'Mauritanie', indicatif: '+222' },
    { nom: 'Mozambique', indicatif: '+258' },
    { nom: 'Namibie', indicatif: '+264' },
    { nom: 'Ouganda', indicatif: '+256' },
    { nom: 'Rwanda', indicatif: '+250' },
    { nom: 'Sao Tomé-et-Principe', indicatif: '+239' },
    { nom: 'Seychelles', indicatif: '+248' },
    { nom: 'Sierra Leone', indicatif: '+232' },
    { nom: 'Somalie', indicatif: '+252' },
    { nom: 'Soudan', indicatif: '+249' },
    { nom: 'Tanzanie', indicatif: '+255' },
    { nom: 'Tchad', indicatif: '+235' },
    { nom: 'Tunisie', indicatif: '+216' },
    { nom: 'Zambie', indicatif: '+260' },
    { nom: 'Zimbabwe', indicatif: '+263' }
  ];
  